version: '3.8'

services:
  #************** START FRONTEND **************
  frontend:
    build:
      context: ../../
      dockerfile: container/development/Dockerfile.frontend
    expose:
      - 8080
    volumes:
      - ../../frontend:/srv/frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
      - keycloak
    networks:
      - proxy-network
  #************** END FRONTEND **************
  #************** START BACKEND **************
  backend:
    build:
      context: ../../
      dockerfile: container/development/Dockerfile.backend
    restart: always
    depends_on:
      - database_backend
    expose:
      - 8080
    volumes:
      - ../../backend:/srv/backend
    environment:
      AUTHORITY: "http://keycloak:8080/auth/realms/Frontend/.well-known/openid-configuration"
      JDBC_URL: "jdbc:postgresql://database_backend:5432/backend"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_MIGRATIONS_LOCATION: filesystem:resources/db/migrations
    networks:
      - proxy-network
      - backend-network
  database_backend:
    image: postgres
    restart: always
    volumes:
      - backend_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=backend
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    expose:
      - 5432
    networks:
      - backend-network
  #************** END BACKEND **************
  #************** START KEYCLOAK **************
  keycloak:
    image: jboss/keycloak:10.0.2
    expose:
      - 8080
    depends_on:
      - database_keycloak
    environment:
      - PROXY_ADDRESS_FORWARDING=true
      - DB_VENDOR=POSTGRES
      - DB_ADDR=database_keycloak
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
      #- KEYCLOAK_USER=admin
      #- KEYCLOAK_PASSWORD=password
    restart: always
    networks:
      - auth-network
      - proxy-network
  database_keycloak:
    image: 'postgres'
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
    expose:
      - 5432
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    networks:
      - auth-network
  #************** END KEYCLOAK **************
  #************** START SWAGGER **************
  swagger_ui:
    image: swaggerapi/swagger-ui
    expose:
      - 8080
    volumes:
      - type: bind
        source: ../../backend/openapi.yml
        target: /usr/share/nginx/html/openapi.yml
        read_only: true
    environment:
      API_URL: openapi.yml
    networks:
      - proxy-network
  #************** END SWAGGER **************
  #************** START NGINX **************
  nginx:
    image: nginx:latest
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    depends_on: 
      - frontend
      - backend
      - keycloak
    networks:
      - proxy-network
    ports:
      - 80:80
      - 443:443
  #************** END NGINX **************
networks:
  auth-network:
    driver: bridge
  proxy-network:
    driver: bridge
  backend-network:
    driver: bridge
volumes:
  keycloak_data:
  backend_data: