FROM rustlang/rust:nightly

RUN cargo install diesel_cli --no-default-features --features postgres

RUN cargo install cargo-watch

WORKDIR /srv/backend

VOLUME ["/usr/local/cargo"]

CMD cargo watch -x run