version: '3.8'

services:
  frontend:
    container_name: 'frontend'
    build:
      context: ../../
      dockerfile: container/development/Dockerfile.frontend
    expose:
      - 8081
    volumes:
      - ../../frontend:/srv/frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
      - keycloak
    networks:
      - proxy-network
  backend:
    container_name: 'backend'
    build:
      context: ../../
      dockerfile: container/development/Dockerfile.backend
    expose:
      - 8082
    volumes:
      - ../../backend:/srv/backend
    depends_on:
      - database_backend
    networks:
      - proxy-network
      - backend-network
  database_backend:
    container_name: database_backend
    image: 'postgres'
    environment:
      - POSTGRES_DB=backend
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
    expose:
      - 5433
    volumes:
      - backend_data:/var/lib/postgresql/data
    networks:
      - backend-network
  database_keycloak:
    container_name: database_keycloak
    image: 'postgres'
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
    expose:
      - 5432
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    networks:
      - auth-network
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:10.0.2
    expose:
      - 8080
    depends_on:
      - database_keycloak
    environment:
      - PROXY_ADDRESS_FORWARDING=true
      - DB_VENDOR=POSTGRES
      - DB_ADDR=database_keycloak
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
      #- KEYCLOAK_USER=admin
      #- KEYCLOAK_PASSWORD=password
    restart: always
    networks:
      - auth-network
      - proxy-network
  nginx:
    image: nginx:latest
    container_name: nginx
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    depends_on: 
      - frontend
      - backend
      - keycloak
    networks:
      - proxy-network
    ports:
      - 80:80
      - 443:443

networks:
  auth-network:
    driver: bridge
  proxy-network:
    driver: bridge
  backend-network:
    driver: bridge

volumes:
  keycloak_data:
  backend_data: