micronaut:
  application:
    name: backend
  security:
    enabled: true
    authentication: bearer
    token:
      jwt:
        signatures:
          jwks:
            keycloak:
              url: "${AUTHORITY}"
datasources:
  default:
    url: ${JDBC_URL}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    schema-generate: CREATE_DROP
    dialect: POSTGRES
