name: Frontend-CI-CD
on:
  push:
    branches:
      - master
    paths:
      - 'frontend/*'
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install and Test
        run: |
          cd frontend
          npm install
          npm validate

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use Node.js 12
        uses: actions/setup-node@master
        with:
          node-version: '12'
      - name: build
        run: |
          cd frontend
          npm install
          npm build
      - uses: actions/upload-artifact@master
        with:
          name: build-files
          path: /frontend/public/

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: use Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - uses: actions/download-artifact@master
        with:
          name: build-files
          path: /frontend/public/